"""add unique constraint and ticker validation

Revision ID: add_unique_constraint_and_validation
Revises: 23c5d33248d2
Create Date: 2026-01-14 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_unique_constraint_and_validation'
down_revision: Union[str, Sequence[str], None] = '23c5d33248d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем уникальный индекс для предотвращения дубликатов
    op.create_index('uq_prices_ticker_ts', 'prices', ['ticker', 'ts'], unique=True)
    
    # Добавляем check constraint для валидации тикеров
    op.create_check_constraint(
        'check_valid_ticker',
        'prices',
        "ticker IN ('btc_usd', 'eth_usd')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_valid_ticker', 'prices', type_='check')
    op.drop_index('uq_prices_ticker_ts', table_name='prices')
    # ### end Alembic commands ###
