"""create_prices_table

Revision ID: b0a105f857ea
Revises: 
Create Date: 2026-01-15 14:18:54.015023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a105f857ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("ticker IN ('eth_usd', 'btc_usd')", name='check_valid_ticker'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prices_ticker_ts', 'prices', ['ticker', 'ts'], unique=False)
    op.create_index('uq_prices_ticker_ts', 'prices', ['ticker', 'ts'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_prices_ticker_ts', table_name='prices')
    op.drop_index('ix_prices_ticker_ts', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
